version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: team_funds
    ports:
      - 3307:3306

  bot:
    image: team_funds
    depends_on:
      - db