version: '3.1'

services:
  db:
    image: postgres:10.6-alpine
    volumes:
      - team_funds-data-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: team_funds
      POSTGRES_PASSWORD: ${TEAM_FUNDS_DB_PASSWORD}
      POSTGRES_USER: ${TEAM_FUNDS_DB_USER}

  bot:
    image: skiclubdeveloper/team_funds
    environment:
      TEAM_FUNDS_DB_URL: ${TEAM_FUNDS_DB_URL}
      TEAM_FUNDS_DB_USER: ${TEAM_FUNDS_DB_USER}
      TEAM_FUNDS_DB_PASSWORD: ${TEAM_FUNDS_DB_PASSWORD}
      TEAM_FUNDS_BOT_TOKEN: ${TEAM_FUNDS_BOT_TOKEN}
      TEAM_FUNDS_BOT_NAME: ${TEAM_FUNDS_BOT_NAME}
    restart: on-failure
    depends_on:
      - db

volumes:
  team_funds-data-volume: