version: '3.1'

services:
  db:
    image: postgres:10.6-alpine
    volumes:
      - team_funds-data-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: team_funds
      POSTGRES_PASSWORD: Anmeldung1.
      POSTGRES_USER: postgres
      PGDATA: /tmp
    ports:
      - 5434:5432

  bot:
    image: skiclubdeveloper/team_funds:v1.2.0
    environment:
      TEAM_FUNDS_DB_URL: jdbc:postgresql://db:5432/team_funds
      TEAM_FUNDS_DB_USER: postgres
      TEAM_FUNDS_DB_PASSWORD: Anmeldung1.
      TEAM_FUNDS_BOT_TOKEN: 762317235:AAGAVpEswx5aAuf8ZjueYfAGCkP7bTy9fIQ
      TEAM_FUNDS_BOT_NAME: skiclub_staging_bot
    restart: on-failure
    depends_on:
      - db

volumes:
  team_funds-data-volume:

